site_name: E-commerce Fullstack
site_url: https://camilascareli.github.io/ecommerce-js/
theme:
  name: material
  language: pt-BR
nav:
  - Do Café à Arte: home.md
  - Visão de Produto e Projeto: visao.md
  - Solução proposta: solucao.md
